### ISSUE TITLE
Bug: website is shifted to the left on Firefox mobile

### ISSUE THREAD

**Issue by nicolo-ribaudo** [SquiggleTools/SquiggleConf#98]
*I'm not using an issue template because the but report template seems to be more for bugs in a library / local bulld. This is about the live website, and even if I were not able to reproduce it locally it would still be relevant.*

## Overview

On Firefox for Android the website:
- is cut on the left, so some text is not readable
- has empty space on the right, so the drop-down menu is in the middle rather than on the right

![Screenshot_2024-08-07-10-59-36-09_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/f3074e24-90af-488b-8097-e5d2006546f2)
![Screenshot_2024-08-07-10-59-39-47_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/ceeb10b1-8d33-4969-a108-fd521f7a8cb9)

It might be relevant that in my phone's accessibility settings I use a larger-than-default font size.

**EDIT:** Chrome has the same behavior

**Comment by nicolo-ribaudo** [comment]
The website is also cut at the bottom. I cannot scroll more than this.
![Screenshot_2024-08-07-11-07-14-38_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/2c42cfe7-dcec-4cc9-8816-06740164c6cf)

**Comment by JoshuaKGoldberg** [comment]
Blugh, lovely. Thanks for reporting. On my local desktop Firefox device emulation, this looks to be happening once the page dips below 400px or so. Working on it!

**Comment by JoshuaKGoldberg** [comment]
Progress: b7b3ad6 fixed issues down to around 350px. Still more work to do...

**Comment by JoshuaKGoldberg** [comment]
Ok! 59a8f02 should get things working down to 320px.

@nicolo-ribaudo are you able to confirm on your end that the site no longer has overflow on mobile for you?

**Comment by nicolo-ribaudo** [comment]
Yes! There is a little bit of horizontal scroll because of the "This Week in React" logo (ideally logos should scale to be at most as wide as the screen), but it's much better now :)

**Comment by JoshuaKGoldberg** [comment]
Awesome thanks! I fixed it just a bit more in bfa4ee4. In theory I'd rather have done better things to get the Astro images to scale, but in practice this ... worked quickly. 😄
